language: csharp
dist: trusty
solution: ./src/Smaragd.sln
dotnet: 2.1
mono: none
install:
  - dotnet restore ./src/Smaragd.sln
script:
  - dotnet build ./src/Smaragd.sln -c Release
  - dotnet test ./src/Smaragd.Tests/Smaragd.Tests.csproj -c Release