name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: windows-latest  
    steps:

    - name: Install .NET 6 preview
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100-preview.1.21103.13

    - name: Checkout
      uses: actions/checkout@v1

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --no-incremental --configuration Release

    - name: Test
      run: dotnet test --no-restore --no-build --configuration Release
